### ISSUE TITLE
Bactopia Roadmap and TODOs

### ISSUE THREAD

**Issue by rpetit3** [bactopia/bactopia#356]
Bactopia is continuously being updated and there are still many things on the roadmap. To be more transparent, I'll document what's planned and what needs to be done. Feel free to make suggestions, and if it's within the scope of Bactopia I'll add it to the list here.

Please keep in mind, at the moment it is just myself maintaining Bactopia, so I cannot guarantee any of these will be implemented. If you want a guarantee, consider contributing to Bactopia, because _teamwork makes the dreamwork!_

## Bug Fixes

- [ ] Large database downloads
- [ ] Roary of Mac (likely related to perl shebang in dependencies)
- [ ] hybrid assembly with short polishing

## New Features

- [ ] check for contamination
- [ ] pick datasets based on taxonomic classifications
- [ ] summary table in TSV
- [ ] MultiQC based report
- [ ] revamped CLI
- [ ] prophage identification
- [ ] Terra.bio integration
- [ ] CGC integration

## Documentation

- [ ] Add ONT examples
- [ ] update docs to most recent version
- [ ] version controlled docs (e.g. see docs at time of v2.0.1)
- [ ] docs to help get started developing Bactopia (#353)
- [ ] how to run on HPC with singularity
- [ ] running on the cloud (AWS, GCP, Azure)

---
_This has been modeled after [rust-bio's](https://github.com/rust-bio/rust-bio) Roadmap/Todos, thank you Johannes!_

**Comment by plasmid02** [comment]
I think a feature where you can enter a sketch of existing species diversity and only process new genomes that are n % distant from exisiting strains.  ie only process samples that are dissimilar to those I have already processed
